appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: ZKlX+8c1NAsIe1rydS5QGzyYAg9Aq2XFpjo/2qA/sO0vT7LGYCxJObQHj7l7GAiJiJicbAyq/ItUOLtaE9lNVeHFudsS47xn644CPkRpM+FazidneHj8agYbASnTQZJBnXoir+RCmsOZ3pr0ARUGb4GKclXt25BOxjG1dcxIJ3NBWmb/0InsDA5TsuGPAUiDgwLIgqi/fphDIn8nEzx5b0kk6Rc5sUUlcsSCyz7Y7XZd5BuJP6tl0LKVcIMMux/DXmQ2tS1y4qeFaB75Fpgzv5rSIVBi7f2W/1Au2FMqThrFGpoeuhb/XuUENMZKJatirGC94bGD2bCvhX8D5439THfriwbSAgu9/aJA3MZgmPtHHmQAjSW+q02PVacOxItLf9vrTV9Tl+ciQpszrZ1Gcz0nK+yBc3il0D/YRVvjJMLDKm3zetx28GhjQ4pYkbRnyA2/AGlNDA5+jSR1c1sZFhM5Q0/dgEVadrluMMBT3eQbRCjzFMaKXnORKXG87pazqfANsn0rVGcCShk1ZT5VS3YWj490zl4/xUKgLrYX2LFwn/w2YjeNQVSrQkbfUjyskc//Es7ifKTUVp64JS6520wCpjY3FrPEojLE4fdmDmFYibsnnXRekVvMhN+Ur7NhLjx3Xshk1HotBdh60WAXEZ5ZaUCh4TjVtPDA6Pn7SfI=
conda_forge_output_validation: true
